# -*- coding: utf-8 -*-
"""Case_tes_fix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13nRuXdue9Xea8XRZIOgrG_wxEtn3tsC4
"""

import script
from script import Transaction

# Instance for test case
trnsct_123 = script.Transaction()

# Test Case 1
print("Test Case 1")

trnsct_123.add_item(["Ayam Goreng", 2, 20000])
trnsct_123.add_item(["Pasta Gigi", 3, 15000])
print("Item yang dibeli adalah: ", trnsct_123.items)

# Test Case 2
print("Test Case 2")

trnsct_123.delete_item("Pasta Gigi")
print("Item yang dibeli adalah: ", trnsct_123.items)

# Test Case 3
print("Test Case 3")

trnsct_123.reset_transaction()

# Test Case 4
print("Test Case 4")

trnsct_123.add_item(["Ayam goreng", 2, 20000])
trnsct_123.add_item(["Pasta gigi", 3, 15000])
trnsct_123.add_item(["Mainan mobil", 1, 200000])
trnsct_123.add_item(["Mie instan", 5, 3000])
print(trnsct_123.items)
print(" ")

# Test Case 5
print("Test Case 5")

trnsct_123.total_price()
print(" ")

# Test Case 6
print("Test Case 6")
trnsct_123.check_order()